groups:
- name: system.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "Prometheus has detected instance {{ $labels.instance }} is down."


  - alert: HighCPU
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU on {{ $labels.instance }}"


  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"


- name: http.rules
  rules:
  - alert: High5xxRate
    expr: sum(rate(nginx_http_requests_total{status=~"5.."}[1m])) by (instance) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High 5xx rate on {{ $labels.instance }}"


  - alert: HighErrorRate
    expr: sum(rate(nginx_http_requests_total{status=~"4..|5.."}[5m])) by (instance) / sum(rate(nginx_http_requests_total[5m])) by (instance) > 0.05
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High client/server error rate on {{ $labels.instance }}"