server:
  http_listen_port: 9080
  grpc_listen_port: 0


positions:
  filename: /tmp/positions.yaml


clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:
  - job_name: nginx_access
    static_configs:
    - targets: ['localhost']
      labels:
        job: nginx_access
        __path__: /var/log/nginx/access.log


  - job_name: nginx_error
    static_configs:
    - targets: ['localhost']
      labels:
        job: nginx_error
        __path__: /var/log/nginx/error.log


  - job_name: docker_containers
    static_configs:
    - targets: ['localhost']
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*.log