---
- name: Remove Database
  hosts: nodes
  vars_files:
    - vars.yaml
  roles:
    - common
    - ssh
  tasks:
    - name: Init DB
      ansible.builtin.import_role:
        name: postgres.clean
      vars:
        db_name: "{{ rumpf_db_name }}"
        postgres_user: "{{ pg_user }}"
        userList: "{{users}}"
    - name: Init DB
      ansible.builtin.import_role:
        name: postgres.clean
      vars:
        db_name: "{{ rumpf_db_name }}"
        postgres_user: "{{ pg_user }}"
        userList: "{{users}}"