---

sql_conf_files_path: /home/ansible/myAnsible/submoduls/CampKraken/Moduls/Rumpf/
sql_conf_files: 
  - schema.sql
  - updates.sql
  - data.sql


sql_conf_files_Check_Bypass: 
  - func.sql

  # Install



user_dorpdown_file: dropdown.yaml
name_ausguck_file: ausguck.yaml
name_ausguck_func_owner_file: ausguckFuncOwner.yaml
name_ausguck_tester_file: ausguckTester.yaml

users:
  - name: "{{user_dropdown_name}}"
    password: "{{user_dorpdown_pw}}"
    file: "{{user_dorpdown_file}}"
  - name: "{{user_ausguck_name}}"
    password: "{{name_ausguck_pw}}"
    file: "{{name_ausguck_file}}"
  - name: "{{user_ausguck_func_owner_name}}"
    password: "{{name_ausguck_func_owner_pw}}"
    file: "{{name_ausguck_func_owner_file}}"
  - name: "{{user_ausguck_tester_name}}"
    password: "{{name_ausguck_tester_pw}}"
    file: "{{name_ausguck_tester_file}}"

