global:
  resolve_timeout: 5m
route:
  receiver: 'pager'
receivers:
- name: 'pager'
  email_configs:
    - to: '${ALERTMANAGER_SMTP_TO}'
      from: '${ALERTMANAGER_SMTP_FROM}'
      smarthost: 'localhost:25'
      require_tls: false


# FÃ¼r produktiven Einsatz: konfiguriere SMTP/Telegram/PagerDuty/etc entsprechend.